/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        brand: "#C29340",
        brandLight:"#EADDC7",
        brandDark: "#AF9362",
        lighter: "#FFFDFA",
        light: "#F1ECE5",
        subTextColor: "#8e8e8e",
        primaryColor: "#222222",
        secondaryColor: "#555555",
        thirdColor: "#757575",
        fourthColor: "#393939",
        darkGray: "#333",
        lightGray: "#555",
        lighterGray: "#777",
        disabled: "#D2D2D2",
        disabledInput: "#F5F5F5",
        disabledText: "#9F9F9F",
        inputBorder: "#FFD488",
        brandError: "#F56B63",
        profileDropdownBg: "#EFEFEF",
        navColor: "#2F2F2F",
        navLinkMobile: "#515151",
        successcolor: "#209E52",
        errorcolor: "#EA4646",
        dropdownText: "#272727",
        chartFirst: "#c5a265",
        chartSecond: "#EADF83",
        chartThird: "#706698",
        lighterBorder: "#EDD5AB",
        disabledLightBorder: "#DADADA",
        lightBorder: "#E2D2B4",
        dashBorder: "#9A9A9A",
        btnDisableBg: "#f2f2f2",
        btnDisableBorder: "#f3f3f3",
        progressColor: "#5c537c",
      },
    },
  },
  plugins: [],
};
